name: Auto Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-2022
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v2
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            buildprops:
              - 'Directory.Build.props'

      - name: NuGet restore
        run: nuget restore rdpWrapper.sln

      - name: Build
        run: |
          msbuild rdpWrapper.sln /t:restore /p:RestorePackagesConfig=true /p:Configuration=Release /p:Platform="Any CPU"
          msbuild rdpWrapper.sln /t:Rebuild /p:DebugType=None /p:Configuration=Release /p:Platform="Any CPU"
          msbuild rdpWrapper.sln /t:Rebuild /p:DebugType=None /p:Configuration=ReleaseLite /p:Platform="Any CPU"
          msbuild rdpWrapper.sln /t:restore /p:RestorePackagesConfig=true /p:Configuration=Release /p:Platform="x64"
          msbuild rdpWrapper.sln /t:Rebuild /p:DebugType=None /p:Configuration=Release /p:Platform="x64"
          msbuild rdpWrapper.sln /t:Rebuild /p:DebugType=None /p:Configuration=ReleaseLite /p:Platform="x64"
          msbuild rdpWrapper.sln /t:restore /p:RestorePackagesConfig=true /p:Configuration=Release /p:Platform="x86"
          msbuild rdpWrapper.sln /t:Rebuild /p:DebugType=None /p:Configuration=Release /p:Platform="x86"
          msbuild rdpWrapper.sln /t:Rebuild /p:DebugType=None /p:Configuration=ReleaseLite /p:Platform="x86"

      - name: upload-unsigned-artifact
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@v4
        with: 
          name: unsigned
          path: rdpWrapper/bin/*.exe

      - name: Debug secrets
        run: |
          echo "ORG_ID is set: ${{ secrets.SIGNPATH_ORG_ID != '' }}"

      - id: optional_step_id
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '${{ secrets.SIGNPATH_ORG_ID }}'
          project-slug: 'rdpWrapper'
          signing-policy-slug: 'test-signing'
          github-artifact-id: '${{ steps.upload-unsigned-artifact.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'rdpWrapper/bin/signed'
          # parameters: |
          #   version: ${{ toJSON(some.userinput) }}
          #   myparam: "another param"

      - name: Publish build
        uses: actions/upload-artifact@v4
        with:
          name: rdpWrapper
          path: |
            rdpWrapper/bin/signed
            